### ISSUE TITLE
Language Server shows no Problems when using lombok

### ISSUE THREAD

**Issue by rkunschke** [GabrielBB/vscode-lombok#7] opened 2018-08-01 13:45 UTC
Hi, since i addet lombok as addon and maven depency i get not errors from the language server. Seems to be a problem with the classpath?
"java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"/home/reinhard/.vscode/extensions/gabrielbb.vscode-lombok-0.9.4/server/lombok.jar\" -Xbootclasspath/a:\"/home/reinhard/.vscode/extensions/gabrielbb.vscode-lombok-0.9.4/server/lombok.jar\"",
This is from my settings
The paths are correct.

**Comment by DavyGuedes** [comment] 2019-05-03 22:18
[Here](https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125) has a workaround. 


> Finally I got it woking. The issue is with the additional argument -Xbootclasspath added by the lombok extension to the java.jdt.ls.vmargs. I figured it out by integrating the lombok with eclipse and opened the eclipse.ini file for the changes.

> - I uninstalled the vscode-lombok extension
> - I downloaded the lombok.jar (version 1.18.6) file from https://projectlombok.org/download
> -  In VSCode, in settings.json, for java.jdt.ls.vmargs key, I added the argument
   -javaagent:\"PATH_TO_DOWNLOADED_LOMBOK_JAR_FILE\"

**Comment by DavyGuedes** [comment] 2019-05-03 22:33
[Here](https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125) has a workaround. 


> Finally I got it woking. The issue is with the additional argument -Xbootclasspath added by the lombok extension to the java.jdt.ls.vmargs. I figured it out by integrating the lombok with eclipse and opened the eclipse.ini file for the changes.

> - I uninstalled the vscode-lombok extension
> - I downloaded the lombok.jar (version 1.18.6) file from https://projectlombok.org/download
> -  In VSCode, in settings.json, for java.jdt.ls.vmargs key, I added the argument
   -javaagent:\"PATH_TO_DOWNLOADED_LOMBOK_JAR_FILE\"

I'm having the same following behavior, but with jdk 12 and Ubuntu 19.04. No compilation errors on vscode, only appear in maven-cli.
https://github.com/redhat-developer/vscode-java/issues/652#issue-364378682

> Finally I got it woking. The issue is with the additional argument **-Xbootclasspath** added by the lombok extension to the **java.jdt.ls.vmargs**. I figured it out by integrating the lombok with eclipse and opened the eclipse.ini file for the changes.
> 
>     * I uninstalled the vscode-lombok extension
> 
>     * I downloaded the lombok.jar (version 1.18.6) file from https://projectlombok.org/download
> 
>     * In VSCode, in settings.json, for **java.jdt.ls.vmargs** key, I added the argument
>       `-javaagent:\"PATH_TO_DOWNLOADED_LOMBOK_JAR_FILE\"`

The problem is in Lombok extension? Should we open a issue in the extension repository? I'm also getting the same behavior in Open JDK 12. Thank you for your workaround. It works!


    Operating System: Ubuntu 19.04
    JDK version: 12
    Visual Studio Code version: 1.33.1
    Java extension version: 0.44.0
 


> ##### Environment
> 
>     * Operating System: macOS High Sierra Version 10.13.6 (17G65)
> 
>     * JDK version: 9/10/11
> 
>     * Visual Studio Code version: 1.27.2 x64
> 
>     * Java extension version: 0.31.0
> 
> 
> ##### Steps To Reproduce
> 
>     1. Set JDK version to 9/10/11 via the `java.home` setting
> 
>     2. Restart editor
> 
>     3. Wait for java language support to boot entirely
> 
>     4. Observe lack of compilation (red underlining etc)
> 
> 
> Project where the issue occurs:
> https://github.com/HedvigInsurance/back-office
> 
> Log output:
> 
> ```
> WARNING: Using incubator modules: jdk.incubator.httpclient
> [Error - 11:15:53 AM] 27 Sep 2018, 11:15:53 Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
> javax/annotation/processing/AbstractProcessor
> java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
> 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
> 	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
> 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
> 	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
> 	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:185)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> [Error - 11:15:57 AM] 27 Sep 2018, 11:15:57 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core".
> javax/annotation/processing/AbstractProcessor
> java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
> 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
> 	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
> 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava5FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:420)
> 	at org.eclipse.jdt.apt.core.internal.AptCompilationParticipant.reconcile(AptCompilationParticipant.java:226)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation$1.run(ReconcileWorkingCopyOperation.java:262)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.notifyParticipants(ReconcileWorkingCopyOperation.java:247)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:99)
> 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
> 	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
> 	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1322)
> 	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1281)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.performValidation(DocumentLifeCycleHandler.java:135)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.access$0(DocumentLifeCycleHandler.java:121)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$1.runInWorkspace(DocumentLifeCycleHandler.java:89)
> 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> [Error - 11:15:57 AM] 27 Sep 2018, 11:15:57 An internal error occurred during: "Validate documents".
> javax/annotation/processing/AbstractProcessor
> java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
> 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
> 	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
> 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava5FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:420)
> 	at org.eclipse.jdt.apt.core.internal.AptCompilationParticipant.reconcile(AptCompilationParticipant.java:226)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation$1.run(ReconcileWorkingCopyOperation.java:262)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.notifyParticipants(ReconcileWorkingCopyOperation.java:247)
> 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:99)
> 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
> 	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
> 	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1322)
> 	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1281)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.performValidation(DocumentLifeCycleHandler.java:135)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.access$0(DocumentLifeCycleHandler.java:121)
> 	at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$1.runInWorkspace(DocumentLifeCycleHandler.java:89)
> 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> [Error - 11:15:58 AM] 27 Sep 2018, 11:15:58 Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
> javax/annotation/processing/AbstractProcessor
> java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
> 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
> 	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
> 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
> 	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
> 	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:185)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> [Error - 11:15:59 AM] 27 Sep 2018, 11:15:59 Errors occurred during the build.
> [Error - 11:15:59 AM] 27 Sep 2018, 11:15:59 Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
> javax/annotation/processing/AbstractProcessor
> java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
> 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
> 	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
> 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
> 	at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
> 	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
> 	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
> 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
> 	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
> 	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
> 	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:185)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> [Error - 11:16:00 AM] 27 Sep 2018, 11:16:00 Errors occurred during the build.
> ```
> 
> ##### Current Result
> 
> No compilation errors
> ##### Expected Result
> 
> Compilation errors
> ##### Additional Informations
> 
> We make heavy use of Lombok, could this be related?

**Comment by GabrielBB** [comment] 2019-05-04 04:17
Fixed with: https://github.com/GabrielBB/vscode-lombok/commit/7e53c6a27eab937a2e223206ab4987e3b80c8260

**Closed by GabrielBB** 2019-05-04 04:17 UTC
